import { TYPE_COFFEE } from "../components/Helpers/helperCoffeeCards"

export interface CoffeeMenuProps {
  id: string
  typeCoffee: keyof typeof TYPE_COFFEE
  tags: string[],
  titleCoffee: string,
  descriptionCoffee: string,
  price: number,
  amount: number
}

export const coffeeMenu = [
  {
    id: "1",
    typeCoffee: "expresso",
    tags: ["Tradicional"],
    titleCoffee: "Expresso Tradicional",
    descriptionCoffee: "O tradicional café feito com água quente e grãos moídos",
    price: 9.90,
    amount: 1,
  },
  {
    id: "2",
    typeCoffee: "americano",
    tags: ["Tradicional"],
    titleCoffee: "Expresso Americano",
    descriptionCoffee: "Expresso diluído, menos intenso que o tradicional",
    price: 9.90,
    amount: 1,
  },
  {
    id: "3",
    typeCoffee: "cremoso",
    tags: ["Tradicional"],
    titleCoffee: "Expresso Cremoso",
    descriptionCoffee: "Café expresso tradicional com espuma cremosa",
    price: 9.90,
    amount: 1,
  },
  {
    id: "4",
    typeCoffee: "gelado",
    tags: ["Tradicional", "Gelado"],
    titleCoffee: "Expresso Gelado",
    descriptionCoffee: "Bebida preparada com café expresso e cubos de gelo",
    price: 9.90,
    amount: 1,
  },
  {
    id: "5",
    typeCoffee: "leite",
    tags: ["Tradicional", "Com Leite"],
    titleCoffee: "Café com Leite",
    descriptionCoffee: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 9.90,
    amount: 1,
  },
  {
    id: "6",
    typeCoffee: "latte",
    tags: ["Tradicional", "Com Leite"],
    titleCoffee: "Latte",
    descriptionCoffee: "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: 9.90,
    amount: 1,
  },
  {
    id: "7",
    typeCoffee: "capuccino",
    tags: ["Tradicional", "Com Leite"],
    titleCoffee: "Capuccino",
    descriptionCoffee: "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 9.90,
    amount: 1,
  },
  {
    id: "8",
    typeCoffee: "macchiato",
    tags: ["Tradicional", "Com Leite"],
    titleCoffee: "Macchiato",
    descriptionCoffee: "Café expresso misturado com um pouco de leite quente e espuma",
    price: 9.90,
    amount: 1,
  },
  {
    id: "9",
    typeCoffee: "mocaccino",
    tags: ["Tradicional", "Com Leite"],
    titleCoffee: "Mocaccino",
    descriptionCoffee: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 9.90,
    amount: 1,
  },
  {
    id: "10",
    typeCoffee: "chocolateQuente",
    tags: ["Especial", "Com Leite"],
    titleCoffee: "Chocolate Quente",
    descriptionCoffee: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 9.90,
    amount: 1,
  },
  {
    id: "11",
    typeCoffee: "cubano",
    tags: ["Especial", "Alcoólico", "Gelado"],
    titleCoffee: "Cubano",
    descriptionCoffee: "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 9.90,
    amount: 1,
  },
  {
    id: "12",
    typeCoffee: "havaiano",
    tags: ["Especial"],
    titleCoffee: "Havaiano",
    descriptionCoffee: "Bebida adocicada preparada com café e leite de coco",
    price: 9.90,
    amount: 1,
  },
  {
    id: "13",
    typeCoffee: "arabe",
    tags: ["Especial"],
    titleCoffee: "Árabe",
    descriptionCoffee: "Bebida preparada com grãos de café árabe e especiarias",
    price: 9.90,
    amount: 1,
  },
  {
    id: "14",
    typeCoffee: "irlandes",
    tags: ["Especial"],
    titleCoffee: "Irlandês",
    descriptionCoffee: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 9.90,
    amount: 1,
  },
] as CoffeeMenuProps[]